### ISSUE TITLE
Rapper cannot be installed Linux (debian based)

### ISSUE THREAD

**Issue by vemonet** [dajobe/raptor#45]
Hi, I wanted to install Raptor/rapper to perform quick convertion of RDF files from the terminal on Ubuntu 20.04 

I found this doc that brought me back 15 years ago: https://librdf.org/raptor/INSTALL.html

Removing all the details about potential options for installation this is the actual lines 98% of people needs to run:

```bash
./autogen.sh
./configure
make 
make install
```

Running `autogen` complains for missing libraries, I started to fix them one by one by running autogen, searched on google, then installing the required library: 

```bash
apt install -y automake libtool gtk-doc-tools
```

Then I arrived at a moment where autogen started to complain about missing "flex", but it seems like I also need to manually build flex: https://github.com/westes/flex and I did not wanted to spend 1 more hour debugging another project that I had no knowledge of.

So I stopped at this level, because I originally just wanted to convert Nquads to Turtle :) 

I was wondering how the people using this library are installing it? Are you also going through this painful manual resolution of dozen of dependencies? Or do you have scripts that helps you to install those? @dajobe 

Is this possible to provide a cleaner way to install this library? Ideally to have it packages using one of the multiple option to package and share packages (`apt`, `snap`)

But a simple script to install the required dependencies easily for common Linux distros would be already a great start! (at least debian so you support most OS used by researchers + windows with WSL)  

Note that there is already a `brew` package to easily install it on MacOS

**Comment by dajobe** [comment]
Binaries available for like 10 years on debian and ubuntu

* https://tracker.debian.org/pkg/raptor2
* https://launchpad.net/ubuntu/+source/raptor2
